objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Donor_Id__c</fullName>
        <label>Donor Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Record_Status__c</fullName>
        <label>Record Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/DonorPaymentMethod__c.object
<CustomObject>
    <label>Donor Payment Method</label>
    <nameField>
        <label>Donor Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donor Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>DonorPaymentMethod</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Status__c</fullName>
        <label>Record Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/npe03__Recurring_Donation__c.object
<CustomObject>
    <fields>
        <fullName>DonorPaymentMethod__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Donor Payment Method</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DonorPaymentMethod__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.npe03__Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DonorPaymentMethod__c</referenceTo>
        <relationshipLabel>Recurring Donations</relationshipLabel>
        <relationshipName>Recurring_Donations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Status__c</fullName>
        <label>Record Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>GcScheduleId__c</fullName>
        <externalId>true</externalId>
        <label>GC Schedule ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Record_Status__c</fullName>
        <label>Record Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/DeleteDonor.cls
public with sharing class DeleteDonor {
@AuraEnabled
	public static void DonorDeleteData(Id idVal,string paramType) {
        if(paramType=='Donor'){
            Contact dataContact = [SELECT Id,Donor_Id__c from Contact where Id=:idVal];
            string idData=string.valueOf(dataContact.Donor_Id__c);
            dataContact.Record_Status__c = 'Inactive';
            update dataContact;
            
            List<DonorPaymentMethod__c> datalistPyment = [SELECT Id FROM DonorPaymentMethod__c where Contact__c=:idVal];
            for(DonorPaymentMethod__c data :datalistPyment){
                data.Record_Status__c ='Inactive';
            }
            update datalistPyment;
            
            List<String> RecId = new List<String>();
            List<npe03__Recurring_Donation__c> datalist = [SELECT Id, Name FROM npe03__Recurring_Donation__c where npe03__Contact__c=:idVal];
            for(npe03__Recurring_Donation__c data :datalist){
                data.Record_Status__c ='Inactive';
                RecId.add(data.Id);
            }
            update datalist;
            
            RecurringBatchClass.RecurringData(RecId);
            if (!updation.isfutureupdate) {
                if(idData!=''){
                	GCDeleteAPI.DeleteContactCallout(idData);    
                }
            		//
            }
            //DeleteOpportunity bcn = new DeleteOpportunity(RecId);
            //ID batchprocessid = Database.executeBatch(bcn);
            
           /* Schema.DescribeSObjectResult R = Account.SObjectType.getDescribe();
            for (Schema.ChildRelationship cr: R.getChildRelationships()) 
            {
              system.debug('====child object==='+cr.getChildSObject());
            }
            */
        }
        else if(paramType=='Recurring'){
        	List<String> RecId = new List<String>();
            List<npe03__Recurring_Donation__c> datalist = [SELECT Id FROM npe03__Recurring_Donation__c where Id=:idVal];
            system.debug('inside datalist'+datalist);
            for(npe03__Recurring_Donation__c data :datalist){
                data.Record_Status__c ='Inactive';
                RecId.add(data.Id);
            }
            if(RecId.size()>0){
            	update datalist;   
                RecurringBatchClass.RecurringData(RecId);
                if (!updation.isfutureupdate) {
            		GCDeleteAPI.DeleteCallout(RecId);
            	}
            }
        }
        else if(paramType=='Pledge'){
            List<Opportunity> datalist = [SELECT Id,npsp__Primary_Contact__c, GcScheduleId__c FROM Opportunity where Id=:idVal];
            List<Contact> datalistContact = [SELECT Id,Donor_Id__c FROM Contact where Id=:datalist[0].npsp__Primary_Contact__c];
            List<String> RecIdOppor = new List<String>();
            for(Opportunity data :datalist){
                data.Record_Status__c ='Inactive';
                RecIdOppor.add(data.Id);
            }
            if(RecIdOppor.size()>0){
                update datalist;  
            }
            if(datalist[0].GcScheduleId__c!=null && datalistContact[0].Donor_Id__c!=null){
                if (!updation.isfutureupdate) {
            		GCDeleteAPI.DeleteOpporCallout(string.valueOf(datalist[0].GcScheduleId__c),string.valueOf(datalistContact[0].Donor_Id__c));
            	}
            }else{
                return;
            }
            
        }
    }
}