objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Donor_Id__c</fullName>
        <label>Donor Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/DonorPaymentMethod__c.object
<CustomObject>
    <label>Donor Payment Method</label>
    <nameField>
        <label>Donor Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donor Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>donor_payment_method_id__c</fullName>
        <externalId>true</externalId>
        <label>donor payment method id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/npe03__Recurring_Donation__c.object
<CustomObject>
    <fields>
        <fullName>DonorPaymentMethod__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Donor Payment Method</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DonorPaymentMethod__c.Contact__c</field>
                <operation>equals</operation>
                <valueField>$Source.npe03__Contact__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DonorPaymentMethod__c</referenceTo>
        <relationshipLabel>Recurring Donations</relationshipLabel>
        <relationshipName>Recurring_Donations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GcSignupId__c</fullName>
        <externalId>true</externalId>
        <label>GC Signup ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>GcSignupId__c</fullName>
        <label>GcSignupId</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GcScheduleId__c</fullName>
        <externalId>true</externalId>
        <label>GC Schedule ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/OpportunityCallout.cls
public class OpportunityCallout {
    @Future(callout=true)
	public static Void OpportunityData(List<Id> idVal){
        try{
            system.debug(idVal);
            String AccessToken = GetGcToken.TokenData();
            Opportunity[] OppData=[select Id,GcSignupId__c,GcScheduleId__c,npe03__Recurring_Donation__c,npsp__Primary_Contact__c,Amount,CloseDate from Opportunity where Id =:idVal];
            Contact[] ContactData=[select Id,Donor_Id__c from Contact where Id =:OppData.get(0).npsp__Primary_Contact__c];
            string ReccuringId = string.valueOf(OppData.get(0).npe03__Recurring_Donation__c);
            npe03__Recurring_Donation__c[] CampQuery = [select Id,DonorPaymentMethod__c from npe03__Recurring_Donation__c where Id=:ReccuringId];
            String PMTId = CampQuery.get(0).DonorPaymentMethod__c;
            DonorPaymentMethod__c[] PMTData = [select donor_payment_method_id__c from DonorPaymentMethod__c where Id=:PMTId];
            String PMTDataVal = string.valueOf(PMTData.get(0).donor_payment_method_id__c);
            string donorPaymentScheduleId = string.valueOf(OppData.get(0).GcScheduleId__c);
            string donorEventsId = (string.valueOf(OppData.get(0).GcSignupId__c) == null) ? '' : string.valueOf(OppData.get(0).GcSignupId__c);
            string gcid = (string.valueOf(ContactData.get(0).Donor_Id__c) == null) ? '' : string.valueOf(ContactData.get(0).Donor_Id__c);
			string amount = (string.valueOf(OppData.get(0).Amount) == null) ? '' : string.valueOf(OppData.get(0).Amount);
			string dateVal = (string.valueOf(OppData.get(0).CloseDate) == null) ? '' : string.valueOf(OppData.get(0).CloseDate);
            
            String PostString='{"donorEventsId":"'+donorEventsId+'","editAllSchedule":"false","gcid":"'+gcid+'","amount":"'+amount+'","donorPaymentScheduleId":"'+donorPaymentScheduleId+'","date":"'+dateVal+'","donorPaymentMethodId":"'+PMTDataVal+'"}';
            
            Http http = new Http();
            HttpRequest req = new HttpRequest();
            req.setEndpoint(Label.GcURL+'editPaymentSchedule');
            req.setMethod('POST');
            req.setHeader('Content-Type', 'application/json;charset=UTF-8');
            req.setHeader('Authorization', 'Bearer '+AccessToken);  
            req.setBody(PostString);
            HttpResponse ResCreate = http.send(req);
            string strRes=ResCreate.getBody();
            JSONParser parserResult =JSON.createParser(strRes);
            system.debug(PostString);
            system.debug(ResCreate);
            system.debug(strRes);
            String valRes = String.valueOf(ResCreate.getStatusCode()); 
        }catch(exception e){
            system.debug(String.valueOf(e));
        }
        
    }
}